articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('new/', views.ArticleCreateView.as_view(), name='article_new'),
    path('<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_edit'), 
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'), 
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'), 
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('', include('articles.urls')),
    path('pages/', include("pages.urls")),

    path('accounts/', include('django.contrib.auth.urls')),

]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

articles/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:article_detail', args=[str(self.id)])

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=150)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('articles:article_list')

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('username', 'email', 'age',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age',)

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Article


# Create your views here.
class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'article_list.html'
    login_url = 'login'


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'article_detail.html'
    login_url = 'login'


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'body',)
    template_name = 'article_edit.html'
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article_list')
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'article_new.html'
    fields = ('title', 'body')
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

articles/templates/article_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml- " type="submit">Confirm</button>
</form>
{% endblock content %}

articles/templates/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
</div>
<p><a href="{% url 'articles:article_edit' article.pk %}">Edit</a> |
    <a href="{% url 'articles:article_delete' article.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'articles:article_list' %}">All Articles</a>.</p>
{% endblock content %}

articles/templates/article_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info ml- " type="submit">Update</button>
</form>
{% endblock content %}

articles/templates/article_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for article in object_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author }} |
        {{ article.date }}</span>
    </div>
    <div class="card-body">
    {{ article.body }}
    <p style="padding: 1rem;">
        <a href="{% url 'articles:article_delete' article.pk %}">Delete</a>
        <a href="{% url 'articles:article_edit' article.pk %}">Edit</a> |
    </p>
    </div>
   
    <div class="card-footer">
        {% for comment in article.comments.all %}
        <p>
            <span class="font-weight-bold">{{ comment.author }} &middot;</span>
            {{ comment }}
        </p>
        {% endfor %}
    </div>
</div>
<br />
{% endfor %}
{% endblock content %}

articles/templates/article_new.html
{% extends 'base.html' %}

{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success ml- " type="submit">Save</button>
</form>
{% endblock content %}

users/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale= , shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{% block title %}Newspaper App{% endblock title %}</title>  
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 ">
      <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="{% url 'articles:article_new' %}">+ New</a></li>
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

users/templates/home.html
{% extends 'base.html' %} 
{% load bootstrap4 %}

{% block title %}Home{% endblock title %} 

{% block content %} 

<!-- {% if user.is_authenticated %} Hi {{ user.username }}!
    <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}  -->

<div class="jumbotron">
    <h1 class="display- ">Newspaper app</h1>
    <p class="lead">A Newspaper website built with Django.</p>
    <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'articles:article_list' %}"
    role="button">View All Articles</a>
    </p>
</div>

{% endblock content %}

users/templates/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %} 

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %} {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>

{% endblock content %}